helm upgrade --install -f ./values.yaml loki loki/loki-stack \
    --namespace=monitoring \
    --timeout 600s \
    --set grafana.enabled=true \
    --set prometheus.enabled=true \
    --set prometheus.server.persistentVolume.existingClaim=loki-prometheus-data \
    --set prometheus.alertmanager.persistentVolume.existingClaim=loki-prometheus-alertmanager-data \
    --set loki.persistence.enabled=true \
    --set loki.persistence.existingClaim=loki-loki-server \
    --set loki.config.table_manager.retention_deletes_enabled=true \
    --set loki.config.table_manager.retention_period=672h \
    --set grafana.persistence.enabled=true \
    --set grafana.persistence.type=pvc \
    --set grafana.persistence.existingClaim=loki-grafana-server \
    --set grafana.grafana.ini.smtp.enabled=true \
    --set grafana.smtp.host=mail-serveri.connection-telecom.com:25
