apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-loki-server
  namespace: monitoring
  labels:
    name: loki-loki
    app: loki
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storagejhb/loki/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jt-nkube02
          - jt-nkube03
          - jt-nkube04
          - jt-nkube05
