apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-prometheus-server
  namespace: monitoring
  labels:
    name: loki-prometheus
    release: loki
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      name: loki-prometheus
