apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-prometheus-alertmanager-data
  namespace: monitoring
  labels:
    name: loki-prometheus-alertmanager
    release: loki
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: loki-prometheus-alertmanager
